FROM ubuntu:18.04
RUN apt-get update 
RUN apt-get install -y build-essential git curl gawk texinfo expat \
    libexpat1-dev bison flex libz-dev python autoconf
# Prepare to download and compile RISCV toolchain
ENV HOME_DIR=/home/root
ENV RISCV_SRC_DIR=$HOME_DIR/riscv-gnu-toolchain
ENV RISCV_DIR=$HOME_DIR/riscv-tools
RUN mkdir -p $HOME_DIR
WORKDIR $HOME_DIR
RUN git clone --recursive https://github.com/riscv/riscv-gnu-toolchain -j $(nproc)
WORKDIR $RISCV_SRC_DIR
# Checkout a specific hash to keep the output binaries consistent
WORKDIR git checkout 23a038856764808d75b6afe96f649980609ae4c6 
# Downloading the prereqs must be done in riscv-gcc folder
WORKDIR $RISCV_SRC_DIR/riscv-gcc 
RUN ./contrib/download_prerequisites 
WORKDIR $RISCV_SRC_DIR 
RUN ./configure --prefix=$RISCV_DIR 
RUN make -j $(nproc)
# Remove the source code
RUN rm -rf $RISCV_SRC_DIR 

# For x86: gcc
# For ARM: arm-linux-gnueabi-gcc or arm-linux-gnueabihf-gcc ?
# For RISCV: $RISCV_DIR/bin/riscv64-unknown-elf-gcc
